# Generated by Django 4.1 on 2022-09-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_data_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
